TrajectoryPlannerROS:

  holonomic_robot: false
  meter_scoring: true

  yaw_goal_tolerance: 0.05
  xy_goal_tolerance: 0.1

  pdist_scale: 0.5
  gdist_scale: 1.0

  max_vel_x: 0.5
  min_vel_x: 0.1

  max_vel_theta: 0.5
  min_vel_theta: -0.5

  acc_lim_theta: 0.5
  acc_lim_x: 0.5
  acc_lim_y: 0.5

  min_in_place_vel_theta: 0.4

  controller_frequency: 10